from gi.repository import GObject

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

class Application(GObject.Object):
    def get_key(self, key=None): ...
    def launch(self): ...
    def fuzzy_match(self, term=None, result=None): ...
    def exact_match(self, term=None, result=None): ...
    def get_app(self): ...
    def set_app(self, value=None): ...
    def get_frequency(self): ...
    def set_frequency(self, value=None): ...
    def get_name(self): ...
    def get_entry(self): ...
    def get_description(self): ...
    def get_wm_class(self): ...
    def get_executable(self): ...
    def get_icon_name(self): ...
    def get_keywords(self, result_length1=None): ...
    def get_categories(self, result_length1=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ApplicationClass:
    @property
    def parent_class(self): ...

class ApplicationPrivate: ...

class Apps(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def fuzzy_score(self, search=None, a=None): ...
    def exact_score(self, search=None, a=None): ...
    def fuzzy_query(self, search=None): ...
    def exact_query(self, search=None): ...
    def reload(self): ...
    def get_show_hidden(self): ...
    def set_show_hidden(self, value=None): ...
    def get_list(self): ...
    def get_min_score(self): ...
    def set_min_score(self, value=None): ...
    def get_name_multiplier(self): ...
    def set_name_multiplier(self, value=None): ...
    def get_entry_multiplier(self): ...
    def set_entry_multiplier(self, value=None): ...
    def get_executable_multiplier(self): ...
    def set_executable_multiplier(self, value=None): ...
    def get_description_multiplier(self): ...
    def set_description_multiplier(self, value=None): ...
    def get_keywords_multiplier(self): ...
    def set_keywords_multiplier(self, value=None): ...
    def get_categories_multiplier(self): ...
    def set_categories_multiplier(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class AppsClass:
    @property
    def parent_class(self): ...

class AppsPrivate: ...

class Score:
    @property
    def name(self): ...
    @property
    def entry(self): ...
    @property
    def executable(self): ...
    @property
    def description(self): ...
    @property
    def keywords(self): ...
    @property
    def categories(self): ...
