from gi.repository import GObject

class Available:
    UNKNOWN: int
    NO: int
    YES: int

class DeviceType:
    UNKNOWN: int
    AUDIO_DEVICE: int
    VIDEO_DEVICE: int

class Direction:
    INPUT: int
    OUTPUT: int

MAJOR_VERSION: int
MICRO_VERSION: int
MINOR_VERSION: int

class MediaCategory:
    UNKNOWN: int
    PLAYBACK: int
    CAPTURE: int
    DUPLEX: int
    MONITOR: int
    MANAGER: int

class MediaClass:
    UNKNOWN: int
    AUDIO_SOURCE: int
    AUDIO_SINK: int
    STREAM_INPUT_AUDIO: int
    STREAM_OUTPUT_AUDIO: int
    VIDEO_SOURCE: int
    VIDEO_SINK: int
    STREAM_INPUT_VIDEO: int
    STREAM_OUTPUT_VIDEO: int
    AUDIO_SOURCE_VIRTUAL: int

class MediaRole:
    UNKNOWN: int
    MOVIE: int
    MUSIC: int
    CAMERA: int
    SCREEN: int
    COMMUNICATION: int
    GAME: int
    NOTIFICATION: int
    DSP: int
    PRODUCTION: int
    ACCESSIBILITY: int
    TEST: int

class NodeState:
    ERROR: int
    CREATING: int
    SUSPENDED: int
    IDLE: int
    RUNNING: int

class Scale:
    LINEAR: int
    CUBIC: int

VERSION: str

def device_type_from_string(string=None): ...
def device_type_to_string(device_type=None): ...
def get_default(): ...
def media_category_from_string(string=None): ...
def media_category_to_string(category=None): ...
def media_class_from_string(string=None): ...
def media_class_to_string(media_class=None): ...
def media_role_from_string(string=None): ...
def media_role_to_string(role=None): ...

class Audio(GObject.Object):
    def __init__(self, wp=None) -> None: ...
    @staticmethod
    def new(wp=None): ...
    def get_default_microphone(self): ...
    def get_default_speaker(self): ...
    def get_device(self, id=None): ...
    def get_devices(self): ...
    def get_microphone(self, id=None): ...
    def get_microphones(self): ...
    def get_node(self, id=None): ...
    def get_recorder(self, id=None): ...
    def get_recorders(self): ...
    def get_speaker(self, id=None): ...
    def get_speakers(self): ...
    def get_stream(self, id=None): ...
    def get_streams(self): ...

class AudioClass:
    @property
    def parent_class(self): ...

class Channel(GObject.Object):
    def get_name(self): ...
    def get_volume(self): ...
    def get_volume_icon(self): ...
    def set_volume(self, volume=None): ...

class ChannelClass:
    @property
    def parent_class(self): ...

class Device(GObject.Object):
    def get_active_profile_id(self): ...
    def get_description(self): ...
    def get_device_type(self): ...
    def get_form_factor(self): ...
    def get_icon(self): ...
    def get_id(self): ...
    def get_input_route_id(self): ...
    def get_input_routes(self): ...
    def get_output_route_id(self): ...
    def get_output_routes(self): ...
    def get_profile(self, id=None): ...
    def get_profiles(self): ...
    def get_pw_property(self, key=None): ...
    def get_route(self, id=None): ...
    def get_routes(self): ...
    def set_active_profile_id(self, profile_id=None): ...
    def set_route(self, route=None, card_device=None): ...

class DeviceClass:
    @property
    def parent_class(self): ...

class EndpointClass:
    @property
    def parent_class(self): ...

class Node(GObject.Object):
    def metadata_changed(self, key=None, type=None, value=None): ...
    def params_changed(self, id=None): ...
    def get_channels(self): ...
    def get_description(self): ...
    def get_icon(self): ...
    def get_id(self): ...
    def get_lock_channels(self): ...
    def get_media_class(self): ...
    def get_mute(self): ...
    def get_name(self): ...
    def get_path(self): ...
    def get_pw_property(self, key=None): ...
    def get_serial(self): ...
    def get_state(self): ...
    def get_volume(self): ...
    def get_volume_icon(self): ...
    def metadata_changed(self, key=None, type=None, value=None): ...
    def params_changed(self, id=None): ...
    def set_lock_channels(self, lock_channels=None): ...
    def set_mute(self, mute=None): ...
    def set_volume(self, volume=None): ...
    @property
    def parent_instance(self): ...

class NodeClass:
    @property
    def parent_class(self): ...
    @property
    def params_changed(self): ...
    @property
    def metadata_changed(self): ...

class Profile(GObject.Object):
    def get_available(self): ...
    def get_description(self): ...
    def get_index(self): ...
    def get_name(self): ...
    def get_priority(self): ...

class ProfileClass:
    @property
    def parent_class(self): ...

class Route(GObject.Object):
    def get_available(self): ...
    def get_description(self): ...
    def get_device(self): ...
    def get_direction(self): ...
    def get_index(self): ...
    def get_name(self): ...
    def get_priority(self): ...

class RouteClass:
    @property
    def parent_class(self): ...

class Stream(Node):
    def get_media_category(self): ...
    def get_media_role(self): ...
    def get_target_endpoint(self): ...
    def get_target_serial(self): ...
    def set_target_endpoint(self, target=None): ...
    def set_target_serial(self, serial=None): ...

class StreamClass:
    @property
    def parent_class(self): ...

class Video(GObject.Object):
    def __init__(self, wp=None) -> None: ...
    @staticmethod
    def new(wp=None): ...
    def get_device(self, id=None): ...
    def get_devices(self): ...
    def get_recorder(self, id=None): ...
    def get_recorders(self): ...
    def get_sink(self, id=None): ...
    def get_sinks(self): ...
    def get_source(self, id=None): ...
    def get_sources(self): ...
    def get_stream(self, id=None): ...
    def get_streams(self): ...

class VideoClass:
    @property
    def parent_class(self): ...

class Wp(GObject.Object):
    @staticmethod
    def get_default(): ...
    def get_audio(self): ...
    def get_default_microphone(self): ...
    def get_default_speaker(self): ...
    def get_device(self, id=None): ...
    def get_devices(self): ...
    def get_node(self, id=None): ...
    def get_node_by_serial(self, serial=None): ...
    def get_nodes(self): ...
    def get_scale(self): ...
    def get_video(self): ...
    def set_scale(self, scale=None): ...

class WpClass:
    @property
    def parent_class(self): ...

class Endpoint(Node):
    def get_device(self): ...
    def get_device_id(self): ...
    def get_is_default(self): ...
    def get_route(self): ...
    def get_route_id(self): ...
    def get_routes(self): ...
    def set_is_default(self, is_default=None): ...
    def set_route(self, route=None): ...
    def set_route_id(self, route_id=None): ...
