from gi.repository import GObject

class Urgency:
    LOW: int
    NORMAL: int
    CRITICAL: int

class ClosedReason:
    EXPIRED: int
    DISMISSED_BY_USER: int
    CLOSED: int
    UNDEFINED: int

class State:
    DRAFT: int
    SENT: int
    RECEIVED: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...
def send_notification(notification=None, _callback_=None, _callback__target=None): ...
def send_notification_finish(_res_=None): ...

class Action(GObject.Object):
    def __init__(self, id=None, label=None) -> None: ...
    @staticmethod
    def new(id=None, label=None): ...
    def invoke(self): ...
    def get_id(self): ...
    def set_id(self, value=None): ...
    def get_label(self): ...
    def set_label(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ActionClass:
    @property
    def parent_class(self): ...

class ActionPrivate: ...

class Notifd(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_notification(self, id=None): ...
    def get_ignore_timeout(self): ...
    def set_ignore_timeout(self, value=None): ...
    def get_dont_disturb(self): ...
    def set_dont_disturb(self, value=None): ...
    def get_default_timeout(self): ...
    def set_default_timeout(self, value=None): ...
    def get_notifications(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class NotifdClass:
    @property
    def parent_class(self): ...
    @property
    def notified(self): ...
    @property
    def resolved(self): ...

class NotifdPrivate: ...

class Notification(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def dismiss(self): ...
    def expire(self): ...
    def invoke(self, action_id=None): ...
    def add_action(self, action=None): ...
    def set_hint(self, name=None, value=None): ...
    def get_hint(self, name=None): ...
    def get_state(self): ...
    def get_time(self): ...
    def get_id(self): ...
    def set_id(self, value=None): ...
    def get_app_name(self): ...
    def set_app_name(self, value=None): ...
    def get_app_icon(self): ...
    def set_app_icon(self, value=None): ...
    def get_summary(self): ...
    def set_summary(self, value=None): ...
    def get_body(self): ...
    def set_body(self, value=None): ...
    def get_expire_timeout(self): ...
    def set_expire_timeout(self, value=None): ...
    def get_actions(self): ...
    def get_hints(self): ...
    def get_image(self): ...
    def set_image(self, value=None): ...
    def get_action_icons(self): ...
    def set_action_icons(self, value=None): ...
    def get_category(self): ...
    def set_category(self, value=None): ...
    def get_desktop_entry(self): ...
    def set_desktop_entry(self, value=None): ...
    def get_resident(self): ...
    def set_resident(self, value=None): ...
    def get_sound_file(self): ...
    def set_sound_file(self, value=None): ...
    def get_sound_name(self): ...
    def set_sound_name(self, value=None): ...
    def get_suppress_sound(self): ...
    def set_suppress_sound(self, value=None): ...
    def get_transient(self): ...
    def set_transient(self, value=None): ...
    def get_x(self): ...
    def set_x(self, value=None): ...
    def get_y(self): ...
    def set_y(self, value=None): ...
    def get_urgency(self): ...
    def set_urgency(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class NotificationClass:
    @property
    def parent_class(self): ...

class NotificationPrivate: ...
