from gi.repository import AstalIO, Gtk

class MouseButton:
    PRIMARY: int
    MIDDLE: int
    SECONDARY: int
    BACK: int
    FORWARD: int

class WindowAnchor:
    NONE: int
    TOP: int
    RIGHT: int
    LEFT: int
    BOTTOM: int

class Exclusivity:
    NORMAL: int
    EXCLUSIVE: int
    IGNORE: int

class Layer:
    BACKGROUND: int
    BOTTOM: int
    TOP: int
    OVERLAY: int

class Keymode:
    NONE: int
    EXCLUSIVE: int
    ON_DEMAND: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def widget_set_css(widget=None, css=None): ...
def widget_get_css(widget=None): ...
def widget_set_class_names(widget=None, class_names=None, class_names_length1=None): ...
def widget_get_class_names(widget=None): ...
def widget_toggle_class_name(widget=None, class_name=None, condition=None): ...
def widget_set_cursor(widget=None, cursor=None): ...
def widget_get_cursor(widget=None): ...
def widget_set_click_through(widget=None, click_through=None): ...
def widget_get_click_through(widget=None): ...

class Box(Gtk.Box):
    def __init__(self, vertical=None, children=None) -> None: ...
    @staticmethod
    def new(vertical=None, children=None): ...
    def get_vertical(self): ...
    def set_vertical(self, value=None): ...
    def get_children(self): ...
    def set_children(self, value=None): ...
    def get_child(self): ...
    def set_child(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class BoxClass:
    @property
    def parent_class(self): ...

class BoxPrivate: ...

class Button(Gtk.Button):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ButtonClass:
    @property
    def parent_class(self): ...

class ButtonPrivate: ...

class CenterBox(Gtk.Box, Gtk.Buildable):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_vertical(self): ...
    def set_vertical(self, value=None): ...
    def get_start_widget(self): ...
    def set_start_widget(self, value=None): ...
    def get_end_widget(self): ...
    def set_end_widget(self, value=None): ...
    def get_center_widget(self): ...
    def set_center_widget(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class CenterBoxClass:
    @property
    def parent_class(self): ...

class CenterBoxPrivate: ...

class CircularProgress(Gtk.Bin):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_start_at(self): ...
    def set_start_at(self, value=None): ...
    def get_end_at(self): ...
    def set_end_at(self, value=None): ...
    def get_value(self): ...
    def set_value(self, value=None): ...
    def get_inverted(self): ...
    def set_inverted(self, value=None): ...
    def get_rounded(self): ...
    def set_rounded(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class CircularProgressClass:
    @property
    def parent_class(self): ...

class CircularProgressPrivate: ...

class EventBox(Gtk.EventBox):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class EventBoxClass:
    @property
    def parent_class(self): ...

class EventBoxPrivate: ...

class Icon(Gtk.Image):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def lookup_icon(icon=None): ...
    def get_pixbuf(self): ...
    def set_pixbuf(self, value=None): ...
    def get_g_icon(self): ...
    def set_g_icon(self, value=None): ...
    def get_icon(self): ...
    def set_icon(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class IconClass:
    @property
    def parent_class(self): ...

class IconPrivate: ...

class Label(Gtk.Label):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_truncate(self): ...
    def set_truncate(self, value=None): ...
    def get_justify_fill(self): ...
    def set_justify_fill(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class LabelClass:
    @property
    def parent_class(self): ...

class LabelPrivate: ...

class LevelBar(Gtk.LevelBar):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_vertical(self): ...
    def set_vertical(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class LevelBarClass:
    @property
    def parent_class(self): ...

class LevelBarPrivate: ...

class Overlay(Gtk.Overlay):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def add_overlay(self, widget=None): ...
    def get_pass_through(self): ...
    def set_pass_through(self, value=None): ...
    def get_overlay(self): ...
    def set_overlay(self, value=None): ...
    def get_overlays(self): ...
    def set_overlays(self, value=None): ...
    def get_child(self): ...
    def set_child(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class OverlayClass:
    @property
    def parent_class(self): ...

class OverlayPrivate: ...

class Scrollable(Gtk.ScrolledWindow):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_child(self): ...
    def get_hscroll(self): ...
    def set_hscroll(self, value=None): ...
    def get_vscroll(self): ...
    def set_vscroll(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ScrollableClass:
    @property
    def parent_class(self): ...

class ScrollablePrivate: ...

class Slider(Gtk.Scale):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_vertical(self): ...
    def set_vertical(self, value=None): ...
    def get_dragging(self): ...
    def get_value(self): ...
    def set_value(self, value=None): ...
    def get_min(self): ...
    def set_min(self, value=None): ...
    def get_max(self): ...
    def set_max(self, value=None): ...
    def get_step(self): ...
    def set_step(self, value=None): ...
    def get_page(self): ...
    def set_page(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class SliderClass:
    @property
    def parent_class(self): ...

class SliderPrivate: ...

class Stack(Gtk.Stack):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_shown(self): ...
    def set_shown(self, value=None): ...
    def get_children(self): ...
    def set_children(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class StackClass:
    @property
    def parent_class(self): ...

class StackPrivate: ...

class Window(Gtk.Window):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_current_monitor(self): ...
    def get_inhibit(self): ...
    def set_inhibit(self, value=None): ...
    def get_namespace(self): ...
    def set_namespace(self, value=None): ...
    def get_anchor(self): ...
    def set_anchor(self, value=None): ...
    def get_exclusivity(self): ...
    def set_exclusivity(self, value=None): ...
    def get_layer(self): ...
    def set_layer(self, value=None): ...
    def get_keymode(self): ...
    def set_keymode(self, value=None): ...
    def get_gdkmonitor(self): ...
    def set_gdkmonitor(self, value=None): ...
    def get_margin_top(self): ...
    def set_margin_top(self, value=None): ...
    def get_margin_bottom(self): ...
    def set_margin_bottom(self, value=None): ...
    def get_margin_left(self): ...
    def set_margin_left(self, value=None): ...
    def get_margin_right(self): ...
    def set_margin_right(self, value=None): ...
    def set_margin(self, value=None): ...
    def get_monitor(self): ...
    def set_monitor(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class WindowClass:
    @property
    def parent_class(self): ...

class WindowPrivate: ...

class Application(Gtk.Application, AstalIO.Application):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def reset_css(self): ...
    def get_window(self, name=None): ...
    def apply_css(self, style=None, reset=None): ...
    def add_icons(self, path=None): ...
    def request(self, request=None, conn=None): ...
    def request(self, request=None, conn=None): ...
    def get_monitors(self): ...
    def get_windows(self): ...
    def get_gtk_theme(self): ...
    def set_gtk_theme(self, value=None): ...
    def get_icon_theme(self): ...
    def set_icon_theme(self, value=None): ...
    def get_cursor_theme(self): ...
    def set_cursor_theme(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ApplicationClass:
    @property
    def parent_class(self): ...
    @property
    def request(self): ...

class ApplicationPrivate: ...

class ClickEvent:
    def init(self, event=None): ...
    @property
    def release(self): ...
    @property
    def time(self): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def modifier(self): ...
    @property
    def button(self): ...

class HoverEvent:
    def init(self, event=None): ...
    @property
    def lost(self): ...
    @property
    def time(self): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def modifier(self): ...
    @property
    def mode(self): ...
    @property
    def detail(self): ...

class ScrollEvent:
    def init(self, event=None): ...
    @property
    def time(self): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def modifier(self): ...
    @property
    def direction(self): ...
    @property
    def delta_x(self): ...
    @property
    def delta_y(self): ...

class MotionEvent:
    def init(self, event=None): ...
    @property
    def time(self): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def modifier(self): ...
