from gi.repository import AstalIO, GObject, Gio

class AppError:
    NAME_OCCUPIED: int
    TAKEOVER_FAILED: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def acquire_socket(app=None, sock=None): ...
def get_instances(): ...
def quit_instance(instance=None): ...
def open_inspector(instance=None): ...
def toggle_window_by_name(instance=None, window=None): ...
def send_message(instance=None, request=None): ...
def send_request(instance=None, request=None): ...
def read_sock(conn=None, _callback_=None, _callback__target=None): ...
def read_sock_finish(_res_=None): ...
def write_sock(conn=None, response=None, _callback_=None, _callback__target=None): ...
def write_sock_finish(_res_=None): ...
def read_file(path=None): ...
def read_file_async(path=None, _callback_=None, _callback__target=None): ...
def read_file_finish(_res_=None): ...
def write_file(path=None, content=None): ...
def write_file_async(path=None, content=None, _callback_=None, _callback__target=None): ...
def write_file_finish(_res_=None): ...
def monitor_file(path=None, callback=None): ...

class Daemon(Gio.Application, AstalIO.Application):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def request(self, request=None, conn=None): ...
    def request(self, request=None, conn=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class DaemonClass:
    @property
    def parent_class(self): ...
    @property
    def request(self): ...

class DaemonPrivate: ...

class Process(GObject.Object):
    def __init__(self, cmd=None, cmd_length1=None) -> None: ...
    @staticmethod
    def new(cmd=None, cmd_length1=None): ...
    def kill(self): ...
    def signal(self, signal_num=None): ...
    def write(self, _in=None): ...
    def write_async(self, _in=None, _callback_=None, _callback__target=None): ...
    def write_finish(self, _res_=None): ...
    @staticmethod
    def subprocessv(cmd=None, cmd_length1=None): ...
    @staticmethod
    def subprocess(cmd=None): ...
    @staticmethod
    def execv(cmd=None, cmd_length1=None): ...
    @staticmethod
    def exec(cmd=None): ...
    @staticmethod
    def exec_asyncv(cmd=None, cmd_length1=None, _callback_=None, _callback__target=None): ...
    @staticmethod
    def exec_asyncv_finish(_res_=None): ...
    @staticmethod
    def exec_async(cmd=None, _callback_=None, _callback__target=None): ...
    @staticmethod
    def exec_finish(_res_=None): ...
    def get_argv(self, result_length1=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ProcessClass:
    @property
    def parent_class(self): ...

class ProcessPrivate: ...

class Time(GObject.Object):
    @staticmethod
    def interval_prio(interval=None, prio=None, fn=None): ...
    @staticmethod
    def timeout_prio(timeout=None, prio=None, fn=None): ...
    @staticmethod
    def idle_prio(prio=None, fn=None): ...
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def interval(interval=None, fn=None): ...
    @staticmethod
    def timeout(timeout=None, fn=None): ...
    @staticmethod
    def idle(fn=None): ...
    def cancel(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class TimeClass:
    @property
    def parent_class(self): ...

class TimePrivate: ...

class VariableBase(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def emit_changed(self): ...
    def emit_dropped(self): ...
    def emit_error(self, err=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class VariableBaseClass:
    @property
    def parent_class(self): ...

class VariableBasePrivate: ...

class Variable(AstalIO.VariableBase):
    def __init__(self, init=None) -> None: ...
    @staticmethod
    def new(init=None): ...
    def poll(self, interval=None, exec=None, transform=None): ...
    def pollv(self, interval=None, execv=None, execv_length1=None, transform=None): ...
    def pollfn(self, interval=None, fn=None): ...
    def watch(self, exec=None, transform=None): ...
    def watchv(self, execv=None, execv_length1=None, transform=None): ...
    def start_poll(self): ...
    def start_watch(self): ...
    def stop_poll(self): ...
    def stop_watch(self): ...
    def is_polling(self): ...
    def is_watching(self): ...
    def get_value(self, result=None): ...
    def set_value(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class VariableClass:
    @property
    def parent_class(self): ...

class VariablePrivate: ...

class Application:
    def quit(self): ...
    def quit(self): ...
    def inspector(self): ...
    def inspector(self): ...
    def toggle_window(self, window=None): ...
    def toggle_window(self, window=None): ...
    def acquire_socket(self): ...
    def acquire_socket(self): ...
    def request(self, request=None, conn=None): ...
    def request(self, request=None, conn=None): ...
    def get_instance_name(self): ...
    def get_instance_name(self): ...
    def set_instance_name(self, value=None): ...
    def set_instance_name(self, value=None): ...

class ApplicationIface:
    @property
    def parent_iface(self): ...
    @property
    def quit(self): ...
    @property
    def inspector(self): ...
    @property
    def toggle_window(self): ...
    @property
    def acquire_socket(self): ...
    @property
    def request(self): ...
    @property
    def get_instance_name(self): ...
    @property
    def set_instance_name(self): ...
