from gi.repository import GObject

class Primary:
    UNKNOWN: int
    WIRED: int
    WIFI: int

def primary_to_string(self): ...
def primary_from_connection_type(type=None): ...

class State:
    UNKNOWN: int
    ASLEEP: int
    DISCONNECTED: int
    DISCONNECTING: int
    CONNECTING: int
    CONNECTED_LOCAL: int
    CONNECTED_SITE: int
    CONNECTED_GLOBAL: int

def state_to_string(self): ...

class Connectivity:
    UNKNOWN: int
    NONE: int
    PORTAL: int
    LIMITED: int
    FULL: int

def connectivity_to_string(self): ...

class DeviceState:
    UNKNOWN: int
    UNMANAGED: int
    UNAVAILABLE: int
    DISCONNECTED: int
    PREPARE: int
    CONFIG: int
    NEED_AUTH: int
    IP_CONFIG: int
    IP_CHECK: int
    SECONDARIES: int
    ACTIVATED: int
    DEACTIVATING: int
    FAILED: int

def device_state_to_string(self): ...

class Internet:
    CONNECTED: int
    CONNECTING: int
    DISCONNECTED: int

def internet_from_device(device=None): ...
def internet_to_string(self): ...

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class AccessPoint(GObject.Object):
    def get_connections(self): ...
    def get_path(self): ...
    def activate(self, password=None, _callback_=None, _callback__target=None): ...
    def activate_finish(self, _res_=None): ...
    def get_bandwidth(self): ...
    def get_bssid(self): ...
    def get_frequency(self): ...
    def get_last_seen(self): ...
    def get_max_bitrate(self): ...
    def get_strength(self): ...
    def get_icon_name(self): ...
    def get_mode(self): ...
    def get_flags(self): ...
    def get_rsn_flags(self): ...
    def get_wpa_flags(self): ...
    def get_requires_password(self): ...
    def get_ssid(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...
    @property
    def ap(self): ...

class AccessPointClass:
    @property
    def parent_class(self): ...

class AccessPointPrivate: ...

class Network(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_client(self): ...
    def get_wifi(self): ...
    def get_wired(self): ...
    def get_primary(self): ...
    def get_connectivity(self): ...
    def get_state(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class NetworkClass:
    @property
    def parent_class(self): ...

class NetworkPrivate: ...

class Wifi(GObject.Object):
    def scan(self): ...
    def deactivate_connection(self, _callback_=None, _callback__target=None): ...
    def deactivate_connection_finish(self, _res_=None): ...
    def get_device(self): ...
    def set_device(self, value=None): ...
    def get_active_connection(self): ...
    def get_active_access_point(self): ...
    def get_access_points(self): ...
    def get_enabled(self): ...
    def set_enabled(self, value=None): ...
    def get_internet(self): ...
    def get_bandwidth(self): ...
    def get_ssid(self): ...
    def get_strength(self): ...
    def get_frequency(self): ...
    def get_state(self): ...
    def get_icon_name(self): ...
    def get_is_hotspot(self): ...
    def get_scanning(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class WifiClass:
    @property
    def parent_class(self): ...

class WifiPrivate: ...

class Wired(GObject.Object):
    def get_device(self): ...
    def set_device(self, value=None): ...
    def get_speed(self): ...
    def get_internet(self): ...
    def get_state(self): ...
    def get_icon_name(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...
    @property
    def connection(self): ...

class WiredClass:
    @property
    def parent_class(self): ...

class WiredPrivate: ...
