from gi.repository import GObject

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class PowerProfiles(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def hold_profile(self, profile=None, reason=None, application_id=None): ...
    def release_profile(self, cookie=None): ...
    def get_active_profile(self): ...
    def set_active_profile(self, value=None): ...
    def get_icon_name(self): ...
    def get_actions(self, result_length1=None): ...
    def get_active_profile_holds(self, result_length1=None): ...
    def get_performance_degraded(self): ...
    def get_profiles(self, result_length1=None): ...
    def get_version(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class PowerProfilesClass:
    @property
    def parent_class(self): ...

class PowerProfilesPrivate: ...

class Profile:
    @property
    def profile(self): ...
    @property
    def cpu_driver(self): ...
    @property
    def platform_driver(self): ...
    @property
    def driver(self): ...

class Hold:
    @property
    def application_id(self): ...
    @property
    def profile(self): ...
    @property
    def reason(self): ...
