from gi.repository import GObject

class Fullscreen:
    CURRENT: int
    NONE: int
    MAXIMIZED: int
    FULLSCREEN: int

class MonitorTransform:
    NORMAL: int
    ROTATE_90_DEG: int
    ROTATE_180_DEG: int
    ROTATE_270_DEG: int
    FLIPPED: int
    FLIPPED_ROTATE_90_DEG: int
    FLIPPED_ROTATE_180_DEG: int
    FLIPPED_ROTATE_270_DEG: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class Client(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def kill(self): ...
    def focus(self): ...
    def move_to(self, ws=None): ...
    def toggle_floating(self): ...
    def get_address(self): ...
    def get_mapped(self): ...
    def get_hidden(self): ...
    def get_x(self): ...
    def get_y(self): ...
    def get_width(self): ...
    def get_height(self): ...
    def get_workspace(self): ...
    def get_floating(self): ...
    def get_monitor(self): ...
    def get_class(self): ...
    def get_title(self): ...
    def get_initial_class(self): ...
    def get_initial_title(self): ...
    def get_pid(self): ...
    def get_xwayland(self): ...
    def get_pinned(self): ...
    def get_fullscreen(self): ...
    def get_fullscreen_client(self): ...
    def get_swallowing(self): ...
    def get_focus_history_id(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ClientClass:
    @property
    def parent_class(self): ...

class ClientPrivate: ...

class Hyprland(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_monitor(self, id=None): ...
    def get_workspace(self, id=None): ...
    def get_client(self, address=None): ...
    def get_monitor_by_name(self, name=None): ...
    def get_workspace_by_name(self, name=None): ...
    def message(self, message=None): ...
    def message_async(self, message=None, _callback_=None, _callback__target=None): ...
    def message_finish(self, _res_=None): ...
    def dispatch(self, dispatcher=None, args=None): ...
    def move_cursor(self, x=None, y=None): ...
    def sync_monitors(self, _callback_=None, _callback__target=None): ...
    def sync_monitors_finish(self, _res_=None): ...
    def sync_workspaces(self, _callback_=None, _callback__target=None): ...
    def sync_workspaces_finish(self, _res_=None): ...
    def sync_clients(self, _callback_=None, _callback__target=None): ...
    def sync_clients_finish(self, _res_=None): ...
    def get_monitors(self): ...
    def get_workspaces(self): ...
    def get_clients(self): ...
    def get_focused_workspace(self): ...
    def get_focused_monitor(self): ...
    def get_focused_client(self): ...
    def get_binds(self): ...
    def get_cursor_position(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class HyprlandClass:
    @property
    def parent_class(self): ...

class HyprlandPrivate: ...

class Monitor(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def focus(self): ...
    def get_id(self): ...
    def get_name(self): ...
    def get_description(self): ...
    def get_make(self): ...
    def get_model(self): ...
    def get_serial(self): ...
    def get_width(self): ...
    def get_height(self): ...
    def get_refresh_rate(self): ...
    def get_x(self): ...
    def get_y(self): ...
    def get_active_workspace(self): ...
    def get_special_workspace(self): ...
    def get_reserved_top(self): ...
    def get_reserved_bottom(self): ...
    def get_reserved_left(self): ...
    def get_reserved_right(self): ...
    def get_scale(self): ...
    def get_transform(self): ...
    def get_focused(self): ...
    def get_dpms_status(self): ...
    def get_vrr(self): ...
    def get_actively_tearing(self): ...
    def get_disabled(self): ...
    def get_current_format(self): ...
    def get_available_modes(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class MonitorClass:
    @property
    def parent_class(self): ...

class MonitorPrivate: ...

class Bind(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_locked(self): ...
    def set_locked(self, value=None): ...
    def get_mouse(self): ...
    def set_mouse(self, value=None): ...
    def get_release(self): ...
    def set_release(self, value=None): ...
    def get_repeat(self): ...
    def set_repeat(self, value=None): ...
    def get_long_press(self): ...
    def set_long_press(self, value=None): ...
    def get_non_consuming(self): ...
    def set_non_consuming(self, value=None): ...
    def get_has_description(self): ...
    def set_has_description(self, value=None): ...
    def get_modmask(self): ...
    def set_modmask(self, value=None): ...
    def get_submap(self): ...
    def set_submap(self, value=None): ...
    def get_key(self): ...
    def set_key(self, value=None): ...
    def get_keycode(self): ...
    def set_keycode(self, value=None): ...
    def get_catch_all(self): ...
    def set_catch_all(self, value=None): ...
    def get_description(self): ...
    def set_description(self, value=None): ...
    def get_dispatcher(self): ...
    def set_dispatcher(self, value=None): ...
    def get_arg(self): ...
    def set_arg(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class BindClass:
    @property
    def parent_class(self): ...

class BindPrivate: ...

class Position(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_x(self): ...
    def set_x(self, value=None): ...
    def get_y(self): ...
    def set_y(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class PositionClass:
    @property
    def parent_class(self): ...

class PositionPrivate: ...

class Workspace(GObject.Object):
    @staticmethod
    def dummy(id=None, monitor=None): ...
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def focus(self): ...
    def move_to(self, m=None): ...
    def get_id(self): ...
    def get_name(self): ...
    def get_monitor(self): ...
    def get_clients(self): ...
    def get_has_fullscreen(self): ...
    def get_last_client(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class WorkspaceClass:
    @property
    def parent_class(self): ...

class WorkspacePrivate: ...
