from gi.repository import GObject

class Input:
    FIFO: int
    PORTAUDIO: int
    PIPEWIRE: int
    ALSA: int
    PULSE: int
    SNDIO: int
    SHMEM: int
    WINSCAP: int

def get_default(): ...

class Cava(GObject.Object):
    @staticmethod
    def get_default(): ...
    def get_active(self): ...
    def get_autosens(self): ...
    def get_bars(self): ...
    def get_channels(self): ...
    def get_framerate(self): ...
    def get_high_cutoff(self): ...
    def get_input(self): ...
    def get_low_cutoff(self): ...
    def get_noise_reduction(self): ...
    def get_samplerate(self): ...
    def get_source(self): ...
    def get_stereo(self): ...
    def get_values(self): ...
    def set_active(self, active=None): ...
    def set_autosens(self, autosens=None): ...
    def set_bars(self, bars=None): ...
    def set_channels(self, channels=None): ...
    def set_framerate(self, framerate=None): ...
    def set_high_cutoff(self, high_cutoff=None): ...
    def set_input(self, input=None): ...
    def set_low_cutoff(self, low_cutoff=None): ...
    def set_noise_reduction(self, noise=None): ...
    def set_samplerate(self, samplerate=None): ...
    def set_source(self, source=None): ...
    def set_stereo(self, stereo=None): ...

class CavaClass:
    @property
    def parent_class(self): ...
