from gi.repository import GObject, Gio

class PlaybackStatus:
    PLAYING: int
    PAUSED: int
    STOPPED: int

class Loop:
    UNSUPPORTED: int
    NONE: int
    TRACK: int
    PLAYLIST: int

class Shuffle:
    UNSUPPORTED: int
    ON: int
    OFF: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class Mpris(GObject.Object, Gio.ListModel):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_players(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class MprisClass:
    @property
    def parent_class(self): ...

class MprisPrivate: ...

class Player(GObject.Object):
    def __init__(self, name=None) -> None: ...
    @staticmethod
    def new(name=None): ...
    def quit(self): ...
    def toggle_fullscreen(self): ...
    def next(self): ...
    def previous(self): ...
    def pause(self): ...
    def play_pause(self): ...
    def stop(self): ...
    def play(self): ...
    def open_uri(self, uri=None): ...
    def loop(self): ...
    def shuffle(self): ...
    def get_meta(self, key=None): ...
    def get_bus_name(self): ...
    def get_available(self): ...
    def get_can_quit(self): ...
    def get_fullscreen(self): ...
    def get_can_set_fullscreen(self): ...
    def get_can_raise(self): ...
    def get_identity(self): ...
    def get_entry(self): ...
    def get_supported_uri_schemes(self, result_length1=None): ...
    def get_supported_mime_types(self, result_length1=None): ...
    def get_loop_status(self): ...
    def set_loop_status(self, value=None): ...
    def get_shuffle_status(self): ...
    def set_shuffle_status(self, value=None): ...
    def get_rate(self): ...
    def set_rate(self, value=None): ...
    def get_volume(self): ...
    def set_volume(self, value=None): ...
    def get_position(self): ...
    def set_position(self, value=None): ...
    def get_playback_status(self): ...
    def get_minimum_rate(self): ...
    def get_maximum_rate(self): ...
    def get_can_go_next(self): ...
    def get_can_go_previous(self): ...
    def get_can_play(self): ...
    def get_can_pause(self): ...
    def get_can_seek(self): ...
    def get_can_control(self): ...
    def get_metadata(self): ...
    def get_trackid(self): ...
    def get_length(self): ...
    def get_art_url(self): ...
    def get_album(self): ...
    def get_album_artist(self): ...
    def get_artist(self): ...
    def get_lyrics(self): ...
    def get_title(self): ...
    def get_composer(self): ...
    def get_comments(self): ...
    def get_cover_art(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class PlayerClass:
    @property
    def parent_class(self): ...

class PlayerPrivate: ...
