from gi.repository import GObject

MAJOR_VERSION: int
MICRO_VERSION: int
MINOR_VERSION: int
VERSION: str

class Pam(GObject.Object):
    @staticmethod
    def authenticate(password=None, result_callback=None, user_data=None): ...
    @staticmethod
    def authenticate_finish(res=None): ...
    def get_service(self): ...
    def get_username(self): ...
    def set_service(self, service=None): ...
    def set_username(self, username=None): ...
    def start_authenticate(self): ...
    def supply_secret(self, secret=None): ...

class PamClass:
    @property
    def parent_class(self): ...
