from gi.repository import GObject

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class Adapter(GObject.Object):
    def remove_device(self, device=None): ...
    def start_discovery(self): ...
    def stop_discovery(self): ...
    def get_uuids(self, result_length1=None): ...
    def get_discovering(self): ...
    def get_modalias(self): ...
    def get_name(self): ...
    def get_class(self): ...
    def get_address(self): ...
    def get_discoverable(self): ...
    def set_discoverable(self, value=None): ...
    def get_pairable(self): ...
    def set_pairable(self, value=None): ...
    def get_powered(self): ...
    def set_powered(self, value=None): ...
    def get_alias(self): ...
    def set_alias(self, value=None): ...
    def get_discoverable_timeout(self): ...
    def set_discoverable_timeout(self, value=None): ...
    def get_pairable_timeout(self): ...
    def set_pairable_timeout(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class AdapterClass:
    @property
    def parent_class(self): ...

class AdapterPrivate: ...

class Bluetooth(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def toggle(self): ...
    def get_is_powered(self): ...
    def get_is_connected(self): ...
    def get_adapter(self): ...
    def get_adapters(self): ...
    def get_devices(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class BluetoothClass:
    @property
    def parent_class(self): ...
    @property
    def device_added(self): ...
    @property
    def device_removed(self): ...
    @property
    def adapter_added(self): ...
    @property
    def adapter_removed(self): ...

class BluetoothPrivate: ...

class Device(GObject.Object):
    def connect_device(self, _callback_=None, _callback__target=None): ...
    def connect_device_finish(self, _res_=None): ...
    def disconnect_device(self, _callback_=None, _callback__target=None): ...
    def disconnect_device_finish(self, _res_=None): ...
    def connect_profile(self, uuid=None): ...
    def disconnect_profile(self, uuid=None): ...
    def pair(self): ...
    def cancel_pairing(self): ...
    def get_uuids(self, result_length1=None): ...
    def get_connected(self): ...
    def get_legacy_pairing(self): ...
    def get_paired(self): ...
    def get_rssi(self): ...
    def get_adapter(self): ...
    def get_address(self): ...
    def get_icon(self): ...
    def get_modalias(self): ...
    def get_name(self): ...
    def get_appearance(self): ...
    def get_class(self): ...
    def get_connecting(self): ...
    def get_blocked(self): ...
    def set_blocked(self, value=None): ...
    def get_trusted(self): ...
    def set_trusted(self, value=None): ...
    def get_battery_percentage(self): ...
    def get_alias(self): ...
    def set_alias(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class DeviceClass:
    @property
    def parent_class(self): ...

class DevicePrivate: ...
