from gi.repository import AstalGreet, GObject

class ErrorType:
    AUTH_ERROR: int
    ERROR: int

class AuthMessageType:
    VISIBLE: int
    SECRET: int
    INFO: int
    ERROR: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def login(username=None, password=None, cmd=None, _callback_=None, _callback__target=None): ...
def login_finish(_res_=None): ...
def login_with_env(username=None, password=None, cmd=None, env=None, env_length1=None, _callback_=None, _callback__target=None): ...
def login_with_env_finish(_res_=None): ...

class Request(GObject.Object):
    def send(self, _callback_=None, _callback__target=None): ...
    def send_finish(self, _res_=None): ...
    def get_type_name(self): ...
    def get_type_name(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class RequestClass:
    @property
    def parent_class(self): ...

class RequestPrivate: ...

class CreateSession(AstalGreet.Request):
    def __init__(self, username=None) -> None: ...
    @staticmethod
    def new(username=None): ...
    def get_username(self): ...
    def set_username(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class CreateSessionClass:
    @property
    def parent_class(self): ...

class CreateSessionPrivate: ...

class PostAuthMesssage(AstalGreet.Request):
    def __init__(self, response=None) -> None: ...
    @staticmethod
    def new(response=None): ...
    def get_response(self): ...
    def set_response(self, value=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class PostAuthMesssageClass:
    @property
    def parent_class(self): ...

class PostAuthMesssagePrivate: ...

class StartSession(AstalGreet.Request):
    def __init__(self, cmd=None, cmd_length1=None, env=None, env_length1=None) -> None: ...
    @staticmethod
    def new(cmd=None, cmd_length1=None, env=None, env_length1=None): ...
    def get_cmd(self, result_length1=None): ...
    def set_cmd(self, value=None, value_length1=None): ...
    def get_env(self, result_length1=None): ...
    def set_env(self, value=None, value_length1=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class StartSessionClass:
    @property
    def parent_class(self): ...

class StartSessionPrivate: ...

class CancelSession(AstalGreet.Request):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class CancelSessionClass:
    @property
    def parent_class(self): ...

class CancelSessionPrivate: ...

class Response(GObject.Object):
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ResponseClass:
    @property
    def parent_class(self): ...

class ResponsePrivate: ...

class Success(AstalGreet.Response):
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class SuccessClass:
    @property
    def parent_class(self): ...

class SuccessPrivate: ...

class Error(AstalGreet.Response):
    def get_error_type(self): ...
    def get_description(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class ErrorClass:
    @property
    def parent_class(self): ...

class ErrorPrivate: ...

class AuthMessage(AstalGreet.Response):
    def get_message_type(self): ...
    def get_message(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class AuthMessageClass:
    @property
    def parent_class(self): ...

class AuthMessagePrivate: ...
