from gi.repository import GObject

class State:
    UNKNOWN: int
    CHARGING: int
    DISCHARGING: int
    EMPTY: int
    FULLY_CHARGED: int
    PENDING_CHARGE: int
    PENDING_DISCHARGE: int

class Technology:
    UNKNOWN: int
    LITHIUM_ION: int
    LITHIUM_POLYMER: int
    LITHIUM_IRON_PHOSPHATE: int
    LEAD_ACID: int
    NICKEL_CADMIUM: int
    NICKEL_METAL_HYDRIDE: int

class WarningLevel:
    UNKNOWN: int
    NONE: int
    DISCHARGING: int
    LOW: int
    CRITICIAL: int
    ACTION: int

class BatteryLevel:
    UNKNOWN: int
    NONE: int
    LOW: int
    CRITICIAL: int
    NORMAL: int
    HIGH: int
    FULL: int

class Type:
    UNKNOWN: int
    LINE_POWER: int
    BATTERY: int
    UPS: int
    MONITOR: int
    MOUSE: int
    KEYBOARD: int
    PDA: int
    PHONE: int
    MEDIA_PLAYER: int
    TABLET: int
    COMPUTER: int
    GAMING_INPUT: int
    PEN: int
    TOUCHPAD: int
    MODEM: int
    NETWORK: int
    HEADSET: int
    SPEAKERS: int
    HEADPHONES: int
    VIDEO: int
    OTHER_AUDIO: int
    REMOVE_CONTROL: int
    PRINTER: int
    SCANNER: int
    CAMERA: int
    WEARABLE: int
    TOY: int
    BLUETOOTH_GENERIC: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class Device(GObject.Object):
    def __init__(self, path=None) -> None: ...
    @staticmethod
    def new(path=None): ...
    @staticmethod
    def get_default(): ...
    def get_device_type(self): ...
    def get_native_path(self): ...
    def get_vendor(self): ...
    def get_model(self): ...
    def get_serial(self): ...
    def get_update_time(self): ...
    def get_power_supply(self): ...
    def get_online(self): ...
    def get_energy(self): ...
    def get_energy_empty(self): ...
    def get_energy_full(self): ...
    def get_energy_full_design(self): ...
    def get_energy_rate(self): ...
    def get_voltage(self): ...
    def get_charge_cycles(self): ...
    def get_luminosity(self): ...
    def get_time_to_empty(self): ...
    def get_time_to_full(self): ...
    def get_percentage(self): ...
    def get_temperature(self): ...
    def get_is_present(self): ...
    def get_state(self): ...
    def get_is_rechargable(self): ...
    def get_capacity(self): ...
    def get_technology(self): ...
    def get_warning_level(self): ...
    def get_battery_level(self): ...
    def get_icon_name(self): ...
    def get_charging(self): ...
    def get_is_battery(self): ...
    def get_battery_icon_name(self): ...
    def get_device_type_name(self): ...
    def get_device_type_icon(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class DeviceClass:
    @property
    def parent_class(self): ...

class DevicePrivate: ...

class UPower(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    def get_devices(self): ...
    def get_display_device(self): ...
    def get_daemon_version(self): ...
    def get_on_battery(self): ...
    def get_lid_is_closed(self): ...
    def get_lid_is_present(self): ...
    def get_critical_action(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class UPowerClass:
    @property
    def parent_class(self): ...

class UPowerPrivate: ...
