from gi.repository import GObject

class OutputSubpixel:
    UNKNOWN: int
    NONE: int
    HORIZONTAL_RGB: int
    HORIZONTAL_BGR: int
    VERTICAL_RGB: int
    VERTICAL_BGR: int

class OutputTransform:
    NORMAL: int
    ROTATE_90: int
    ROTATE_180: int
    ROTATE_270: int
    FLIPPED: int
    FLIPPED_90: int
    FLIPPED_180: int
    FLIPPED_270: int

class SeatCapabilities:
    POINTER: int
    KEYBOARD: int
    TOUCH: int

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class Registry(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_globals(self): ...
    def get_outputs(self): ...
    def get_seats(self): ...
    def get_registry(self): ...
    def get_display(self): ...
    def find_globals(self, interface=None): ...
    def get_global_by_id(self, id=None): ...
    def get_output_by_id(self, id=None): ...
    def get_output_by_name(self, name=None): ...
    def get_output_by_wl_output(self, wl_output=None): ...
    def get_seat_by_id(self, id=None): ...
    def get_seat_by_name(self, name=None): ...
    def get_seat_by_wl_seat(self, wl_seat=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...
    @property
    def globals(self): ...
    @property
    def outputs(self): ...
    @property
    def seats(self): ...

class RegistryClass:
    @property
    def parent_class(self): ...

class RegistryPrivate: ...

class Output(GObject.Object):
    def get_wl_output(self): ...
    def get_id(self): ...
    def get_geometry(self): ...
    def get_physical_width(self): ...
    def get_physical_height(self): ...
    def get_refresh_rate(self): ...
    def get_transform(self): ...
    def get_subpixel(self): ...
    def get_make(self): ...
    def get_model(self): ...
    def get_scale(self): ...
    def get_name(self): ...
    def get_description(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class OutputClass:
    @property
    def parent_class(self): ...

class OutputPrivate: ...

class Seat(GObject.Object):
    def get_wl_seat(self): ...
    def get_id(self): ...
    def get_name(self): ...
    def get_capabilities(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class SeatClass:
    @property
    def parent_class(self): ...

class SeatPrivate: ...

class Global:
    @property
    def name(self): ...
    @property
    def interface(self): ...
    @property
    def version(self): ...

class Rectangle:
    def init_zero(self): ...
    def copy(self, result=None): ...
    def normalize(self): ...
    @staticmethod
    def intersect(a=None, b=None, _result_=None): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
