from gi.repository import GObject

class Category:
    APPLICATION: int
    COMMUNICATIONS: int
    SYSTEM: int
    HARDWARE: int

def category_to_nick(self): ...
def category_from_string(value=None): ...

class Status:
    PASSIVE: int
    ACTIVE: int
    NEEDS_ATTENTION: int

def status_to_nick(self): ...
def status_from_string(value=None): ...

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def get_default(): ...

class TrayItem(GObject.Object):
    def about_to_show(self): ...
    def activate(self, x=None, y=None): ...
    def secondary_activate(self, x=None, y=None): ...
    def scroll(self, delta=None, orientation=None): ...
    def to_json_string(self): ...
    def get_title(self): ...
    def get_category(self): ...
    def get_status(self): ...
    def get_tooltip(self): ...
    def get_tooltip_markup(self): ...
    def get_tooltip_text(self): ...
    def get_id(self): ...
    def get_is_menu(self): ...
    def get_icon_theme_path(self): ...
    def get_icon_name(self): ...
    def get_icon_pixbuf(self): ...
    def get_gicon(self): ...
    def get_item_id(self): ...
    def get_menu_path(self): ...
    def get_menu_model(self): ...
    def get_action_group(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class TrayItemClass:
    @property
    def parent_class(self): ...

class TrayItemPrivate: ...

class Tray(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def get_item(self, item_id=None): ...
    def get_items(self): ...
    def get_items_model(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class TrayClass:
    @property
    def parent_class(self): ...
    @property
    def item_added(self): ...
    @property
    def item_removed(self): ...

class TrayPrivate: ...

class Pixmap:
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def bytes(self): ...
    @property
    def bytes_length1(self): ...

class Tooltip:
    @property
    def icon_name(self): ...
    @property
    def icon(self): ...
    @property
    def icon_length1(self): ...
    @property
    def title(self): ...
    @property
    def description(self): ...
