from gi.repository import GObject

MAJOR_VERSION: int
MINOR_VERSION: int
MICRO_VERSION: int
VERSION: str

def is_supported(): ...
def get_default(): ...

class River(GObject.Object):
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def new(): ...
    @staticmethod
    def get_default(): ...
    def find_output_by_wl_output(self, wl_output=None): ...
    def find_output_by_astal_wl_output(self, wl_output=None): ...
    def find_output_by_name(self, name=None): ...
    def find_output_by_id(self, id=None): ...
    def run_command(self, cmd=None, cmd_length1=None, output=None): ...
    def run_command_async(self, cmd=None, cmd_length1=None, _callback_=None, _callback__target=None): ...
    def run_command_finish(self, _res_=None, output=None): ...
    def new_layout(self, namespace=None): ...
    def get_outputs(self): ...
    def get_focused_output(self): ...
    def get_focused_output_name(self): ...
    def get_focused_view(self): ...
    def get_mode(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class RiverClass:
    @property
    def parent_class(self): ...

class RiverPrivate: ...

class Output(GObject.Object):
    def get_output(self): ...
    def get_focused_tags(self): ...
    def set_focused_tags(self, value=None): ...
    def get_occupied_tags(self): ...
    def get_urgent_tags(self): ...
    def get_focused_view(self): ...
    def get_layout_name(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...

class OutputClass:
    @property
    def parent_class(self): ...

class OutputPrivate: ...

class LayoutDemandResult(GObject.Object):
    def __init__(self, layout_name=None, rectangles=None) -> None: ...
    @staticmethod
    def new(layout_name=None, rectangles=None): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...
    @property
    def layout_name(self): ...
    @property
    def rectangles(self): ...

class LayoutDemandResultClass:
    @property
    def parent_class(self): ...

class LayoutDemandResultPrivate: ...

class Layout(GObject.Object):
    def set_layout_demand_closure(self, closure=None): ...
    def get_namespace(self): ...
    @property
    def parent_instance(self): ...
    @property
    def priv(self): ...
    @property
    def layout_demand_closure(self): ...

class LayoutClass:
    @property
    def parent_class(self): ...

class LayoutPrivate: ...
